# Step 3: identify how many images we already have for now 

# File input: 
#   `fileListWithPages.json`: a dictionary with five digit number as
#       key to each issue, and each value is a dictionary detailing date, other info
#       and total number of pages of the issue.
#   'onedriveList.txt': a list of files in the onedrive folder. It is generated by `dir /b >
#       ../../Desktop/onedriveList.txt` at the chronicle folder. This script WILL NOT
#       count files in the `SelectedIssues` folder. Should you want that, add /s to
#       the command

# File output: 
#   `fileListWithPagesAndActuralCount.json`: a dictionary with five digit number as
#       key to each issue, and each value is a dictionary detailing date, other info,
#       total number of pages, and existing pages of the issue.


import json


with open('onedriveList.txt') as f:
    onedriveList = list(map(lambda x: x[-13:], filter(lambda x: x[-4:] == '.jpg', f.read().split('\n')[:-1])))

with open('fileListWithPages.json') as f:
    fileList = json.load(f)

for key in fileList:
    fileList[key]['onedriveCount'] = 0

for i in onedriveList:
    key = i[:5]
    issueRecord = fileList[key]

    issueRecord['onedriveCount'] += 1
    

with open('fileListWithPagesAndActuralCount.json', 'w') as f:
    json.dump(fileList, f)